### ISSUE TITLE
prepareElement doesn't work with react-transition-group

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-react#179]
### Type of issue

Bug

### Description

Currently using material ui & Fusion.js results in an error with a stacktrace leading back to fusion-react. It seems that this may be resulting in mismatches when server rendering and hydrating.

We have had multiple reports from open source contributors running into this issue.

### Error message

When using with material-ui:
```
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the TransitionGroup component.
	warningWithoutStack
react.development.js:244
warnNoop
react.development.js:293
enqueueSetState
react.development.js:362
./node_modules/react/cjs/react.development.js/Component.prototype.setState
react.development.js:413
componentWillMount
react-lifecycles-compat.es.js:12
renderCompositeElementInstance
prepare.js:36
prepareElement/<
prepare.js:89
run
es6.promise.js:75
notify/<
es6.promise.js:92
flush
_microtask.js:18

```

When using react-transition-group directly (v2):

```
TypeError: Cannot read property 'bind' of undefined
    at /...node_modules/react-transition-group/utils/ChildMapping.js:142:28
    at Array.forEach ()
    at getNextChildMapping (/...node_modules/react-transition-group/utils/ChildMapping.js:115:25)
    at Function.getDerivedStateFromProps (/...node_modules/react-transition-group/TransitionGroup.js:142:138)
    at TransitionGroup.componentWillMount (/...node_modules/react-lifecycles-compat/react-lifecycles-compat.cjs.js:14:32)
    at componentWillMount (/...node_modules/fusion-react/src/async/prepare.js:36:14)
    at renderCompositeElementInstance (/...node_modules/fusion-react/src/async/prepare.js:89:14)
    at
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

fusion-react@1.3.0

**Comment by KevinGrandon** [comment]
Possibly something in here doesn't agree with our usage of prepare/prepared? https://github.com/reactjs/react-transition-group/blob/8943f40432e60d66ee2b5dc2eb6b660ed5dc9b34/src/TransitionGroup.js#L109-L119
